/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/plugin.module';
import * as import2 from './plugin.component.ngfactory';
import * as import3 from '../../../src/app/plugin.component';
class PluginModuleInjector extends import0.ɵNgModuleInjector<import1.PluginModule> {
  _PluginModule_0:import1.PluginModule;
  _PLUGIN_ENTRY_POINT_1:any;
  constructor(parent:import0.Injector) {
    super(parent,[import2.PluginComponentNgFactory],([] as any[]));
  }
  createInternal():import1.PluginModule {
    this._PluginModule_0 = new import1.PluginModule();
    this._PLUGIN_ENTRY_POINT_1 = import3.PluginComponent;
    return this._PluginModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.PluginModule)) { return this._PluginModule_0; }
    if ((token === 'PLUGIN_ENTRY_POINT')) { return this._PLUGIN_ENTRY_POINT_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PluginModuleNgFactory:import0.NgModuleFactory<import1.PluginModule> = new import0.NgModuleFactory<any>(PluginModuleInjector,import1.PluginModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi1jbGkvc3JjL2FwcC9wbHVnaW4ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4tY2xpL3NyYy9hcHAvcGx1Z2luLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
