/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/plugin.component';
const styles_PluginComponent:any[] = ([] as any[]);
export const RenderType_PluginComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PluginComponent,
  data: {}
}
);
export function View_PluginComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['\n    I am a plugin!\n    I am a changed plugin :D\n\n    ']))],(null as any),(null as any));
}
function View_PluginComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'myplugin',([] as any[]),(null as any),(null as any),(null as any),View_PluginComponent_0,RenderType_PluginComponent)),
    import0.ɵdid(49152,(null as any),0,import1.PluginComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PluginComponentNgFactory:import0.ComponentFactory<import1.PluginComponent> = import0.ɵccf('myplugin',import1.PluginComponent,View_PluginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi1jbGkvc3JjL2FwcC9wbHVnaW4uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4tY2xpL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1Byb2plY3RzL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4tY2xpL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC50cy5QbHVnaW5Db21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL21vZHVsZS1sb2FkaW5nL2R5bmFtaWMvbXlwbHVnaW4tY2xpL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC50cy5QbHVnaW5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICBJIGFtIGEgcGx1Z2luIVxuICAgIEkgYW0gYSBjaGFuZ2VkIHBsdWdpbiA6RFxuXG4gICAgIiwiPG15cGx1Z2luPjwvbXlwbHVnaW4+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQ0FBOzs7O0lDQUE7Z0JBQUE7Ozs7In0=
