/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/plugin.component';
const styles_PluginComponent:any[] = ([] as any[]);
export const RenderType_PluginComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PluginComponent,
  data: {}
}
);
export function View_PluginComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['hi']))],(null as any),(null as any));
}
function View_PluginComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'lazy',([] as any[]),(null as any),(null as any),(null as any),View_PluginComponent_0,RenderType_PluginComponent)),
    import0.ɵdid(57344,(null as any),0,import1.PluginComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PluginComponentNgFactory:import0.ComponentFactory<import1.PluginComponent> = import0.ɵccf('lazy',import1.PluginComponent,View_PluginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2ZhYmlhbndpbGVzL0RvY3VtZW50cy9tb2R1bGUtbG9hZGluZy9keW5hbWljL215cGx1Z2luL3NyYy9hcHAvcGx1Z2luLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9mYWJpYW53aWxlcy9Eb2N1bWVudHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi9zcmMvYXBwL3BsdWdpbi5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9mYWJpYW53aWxlcy9Eb2N1bWVudHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi9zcmMvYXBwL3BsdWdpbi5jb21wb25lbnQudHMuUGx1Z2luQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9mYWJpYW53aWxlcy9Eb2N1bWVudHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi9zcmMvYXBwL3BsdWdpbi5jb21wb25lbnQudHMuUGx1Z2luQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiaGkiLCI8bGF6eT48L2xhenk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQ0FBOzs7O0lDQUE7Z0JBQUE7OztJQUFBOzs7In0=
