/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/plugin.module';
import * as import2 from './plugin.component.ngfactory';
class PluginModuleInjector extends import0.ɵNgModuleInjector<import1.PluginModule> {
  _PluginModule_0:import1.PluginModule;
  constructor(parent:import0.Injector) {
    super(parent,[import2.PluginComponentNgFactory],([] as any[]));
  }
  createInternal():import1.PluginModule {
    this._PluginModule_0 = new import1.PluginModule();
    return this._PluginModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.PluginModule)) { return this._PluginModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PluginModuleNgFactory:import0.NgModuleFactory<import1.PluginModule> = new import0.NgModuleFactory<any>(PluginModuleInjector,import1.PluginModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2ZhYmlhbndpbGVzL0RvY3VtZW50cy9tb2R1bGUtbG9hZGluZy9keW5hbWljL215cGx1Z2luL3NyYy9hcHAvcGx1Z2luLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9mYWJpYW53aWxlcy9Eb2N1bWVudHMvbW9kdWxlLWxvYWRpbmcvZHluYW1pYy9teXBsdWdpbi9zcmMvYXBwL3BsdWdpbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
